# Site settings
title: bckly
email: logan.buckley@gmail.com
description: "Programs about writing, writing about programs."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bckly.com" # the base hostname & protocol for your site
twitter_username: loganmhb
github_username:  loganmhb

# Build settings
markdown: kramdown
highlighter: rouge

permalink: none

kramdown:
  input: GFM
  highlighter: rouge
